export const PUBLIC_DESTINATION_READ_MODEL_TTL_MS = 5 * 60 * 1000;

export const PUBLIC_DESTINATION_PAGE_REVALIDATE_SECONDS = 5 * 60;

export const PUBLIC_DESTINATION_API_S_MAXAGE_SECONDS = 5 * 60;

export const PUBLIC_DESTINATION_API_STALE_WHILE_REVALIDATE_SECONDS =
  10 * 60;
